# Ex2 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv).

### Step 3. Assign it to a variable called euro12.

In [27]:
url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv"


euro12= pd.read_csv(url)

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

### Step 4. Select only the Goal column.

In [28]:
euro12["Goals"]

0      4
1      4
2      4
3      5
4      3
5     10
6      5
7      6
8      2
9      2
10     6
11     1
12     5
13    12
14     5
15     2
Name: Goals, dtype: int64

### Step 5. How many team participated in the Euro2012?

In [29]:
print(euro12.shape[0])

16

16

### Step 6. What is the number of columns in the dataset?

In [33]:
print(len(euro12.columns))

35

### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

In [36]:
discipline = euro12[["Team","Yellow Cards","Red Cards"]].head()
discipline

             Team  Yellow Cards  Red Cards
0         Croatia             9          0
1  Czech Republic             7          0
2         Denmark             4          0
3         England             5          0
4          France             6          0

### Step 8. Sort the teams by Red Cards, then to Yellow Cards

In [38]:
discipline_sorted = discipline.sort_values(by=['Red Cards', 'Yellow Cards'])
discipline_sorted

             Team  Yellow Cards  Red Cards
2         Denmark             4          0
3         England             5          0
4          France             6          0
1  Czech Republic             7          0
0         Croatia             9          0

### Step 9. Calculate the mean Yellow Cards given per Team

In [41]:
discipline["Yellow Cards"].mean()

np.float64(6.2)

### Step 10. Filter teams that scored more than 6 goals

In [42]:

equipos_mas_de_6_goles = euro12[euro12['Goals'] > 6]
equipos_mas_de_6_goles[['Team', 'Goals']]

       Team  Goals
5   Germany     10
13    Spain     12

### Step 11. Select the teams that start with G

In [44]:
equipos_con_G = euro12[euro12['Team'].str.startswith('G')]

equipos_con_G[["Team"]]

      Team
5  Germany
6   Greece

C:\Users\Admin\AppData\Local\Temp/ipykernel_22896/1100048980.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  mask = euro12.Team.str.contains("(^G)")

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20

### Step 12. Select the first 7 columns

In [52]:
euro12.columns[0:8]

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork'],
      dtype='str')

### Step 13. Select all columns except the last 3.

In [54]:
columnasmenos3 = euro12.iloc[:, :-3]

columnasmenos3.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,0,10,3,13,81.3%,41,62,2,9,0
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,1,10,6,9,60.1%,53,73,8,7,0
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,1,10,5,10,66.7%,25,38,8,4,0
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,2,29,3,22,88.1%,43,45,6,5,0
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,1,7,5,6,54.6%,36,51,5,6,0

### Step 14. Present only the Shooting Accuracy from England, Italy and Russia

In [ ]:
equipos_seleccionados = euro12['Team'].head(['England', 'Italy', 'Russia'])

euro12.iloc[equipos_seleccionados,["Team", "Shooting Accuracy"]]


#NOSE COMO

TypeError: cannot do positional indexing on RangeIndex with these indexers [['England', 'Italy', 'Russia']] of type list

Empty DataFrame
Columns: [Team, Shooting Accuracy]
Index: []

3     50.0%
7     43.0%
12    22.5%
Name: Shooting Accuracy, dtype: object